apiVersion: v1
kind: Service
metadata:
  name: {{ include "tvarr.fullname" . }}
  labels:
    {{- include "tvarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.ffmpegd.enabled }}
    - port: {{ .Values.service.grpcPort | default 9090 }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- end }}
  selector:
    {{- include "tvarr.selectorLabels" . | nindent 4 }}
